---
name: traefik2-loadbalancer
title: Traefik v2 (LoadBalancer)
version: "2.9.4"
default: false
maintainer: "johannes@jitesoft.com, saiyam@civo.com"
description: An open source Edge Router working as an ingress controller and load balancer inside your kubernetes cluster.
url: https://traefik.io
category: architecture
required_services:
  - loadbalancer
